In [6]:
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv('/content/Sales (1).csv')

In [8]:
df.head()

,Brands,Models,Colors,Memory,Storage,Camera,Rating,Selling Price,Original Price,Mobile,Discount,discount percentage
0,SAMSUNG,GALAXY M31S,Mirage Black,8 GB,128 GB,Yes,4.3,19330,20999,SAMSUNG GALAXY M31S,1669,7.947998
1,Nokia,3.2,Steel,2 GB,16 GB,Yes,3.8,10199,10199,Nokia 3.2,0,0.000000
2,realme,C2,Diamond Black,2 GB,NaN,Yes,4.4,6999,7999,realme C2,1000,12.501563
3,Infinix,Note 5,Ice Blue,4 GB,64 GB,Yes,4.2,12999,12999,Infinix Note 5,0,0.000000
4,Apple,iPhone 11,Black,4GB,64 GB,Yes,4.6,49900,49900,Apple iPhone 11,0,0.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3114 entries, 0 to 3113
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Brands               3114 non-null   object
 1   Models               3114 non-null   object
 2   Colors               3114 non-null   object
 3   Memory               3071 non-null   object
 4   Storage              3075 non-null   object
 5   Camera               3114 non-null   object
 6   Rating               2970 non-null   float64
 7   Selling Price        3114 non-null   int64
 8   Original Price       3114 non-null   int64
 9   Mobile               3114 non-null   object
 10  Discount             3114 non-null   int64
 11  discount percentage  3114 non-null   float64
dtypes: float64(2), int64(3), object(7)
memory usage: 292.1+ KB

In [10]:
df.isnull().sum()

Brands                   0
Models                   0
Colors                   0
Memory                  43
Storage                 39
Camera                   0
Rating                 144
Selling Price            0
Original Price           0
Mobile                   0
Discount                 0
discount percentage      0
dtype: int64

In [11]:
df.shape

(3114, 12)

In [12]:
# Drop the camera column
df.drop('Camera', axis=1, inplace=True)

In [13]:
df.head(10)

,Brands,Models,Colors,Memory,Storage,Rating,Selling Price,Original Price,Mobile,Discount,discount percentage
0,SAMSUNG,GALAXY M31S,Mirage Black,8 GB,128 GB,4.3,19330,20999,SAMSUNG GALAXY M31S,1669,7.947998
1,Nokia,3.2,Steel,2 GB,16 GB,3.8,10199,10199,Nokia 3.2,0,0.000000
2,realme,C2,Diamond Black,2 GB,NaN,4.4,6999,7999,realme C2,1000,12.501563
3,Infinix,Note 5,Ice Blue,4 GB,64 GB,4.2,12999,12999,Infinix Note 5,0,0.000000
4,Apple,iPhone 11,Black,4GB,64 GB,4.6,49900,49900,Apple iPhone 11,0,0.000000
5,GIONEE,L800,Black,8 MB,16 MB,4.0,2199,2199,GIONEE L800,0,0.000000
6,Apple,iPhone 13 Mini,Pink,6 GB,512 GB,NaN,99900,99900,Apple iPhone 13 Mini,0,0.000000
7,Apple,iPhone XR,Coral,3 GB,64 GB,4.6,42999,47900,Apple iPhone XR,4901,10.231733
8,SAMSUNG,Galaxy E5,Brown,1.5 GB,16 GB,4.2,20400,20400,SAMSUNG Galaxy E5,0,0.000000
9,Xiaomi,Redmi Note 11T 5G,Aquamarine Blue,8 GB,128 GB,4.3,21736,22999,Xiaomi Redmi Note 11T 5G,1263,5.491543

In [14]:
df.shape

(3114, 11)

In [15]:
df.describe()

,Rating,Selling Price,Original Price,Discount,discount percentage
count,2970.000000,3114.000000,3114.000000,3114.000000,3114.000000
mean,4.243098,26436.625562,28333.473025,1896.847463,6.086788
std,0.271991,30066.892622,31525.599889,5337.126176,11.106776
min,2.300000,1000.000000,1000.000000,-8000.000000,-160.320641
25%,4.100000,9990.000000,10030.250000,0.000000,0.000000
50%,4.300000,15000.000000,16889.500000,0.000000,0.000000
75%,4.400000,28999.000000,31500.000000,2000.000000,9.836388
max,5.000000,179900.000000,189999.000000,75000.000000,70.610305

In [16]:
# count duplicates in models and Mobile columns
df.duplicated(subset=['Models', 'Mobile']).sum()

np.int64(2186)

In [17]:
# drop duplicates in the models and mobile column
df.drop_duplicates(subset=['Models', 'Mobile'], inplace=True)

In [18]:
df.head(10)

,Brands,Models,Colors,Memory,Storage,Rating,Selling Price,Original Price,Mobile,Discount,discount percentage
0,SAMSUNG,GALAXY M31S,Mirage Black,8 GB,128 GB,4.3,19330,20999,SAMSUNG GALAXY M31S,1669,7.947998
1,Nokia,3.2,Steel,2 GB,16 GB,3.8,10199,10199,Nokia 3.2,0,0.000000
2,realme,C2,Diamond Black,2 GB,NaN,4.4,6999,7999,realme C2,1000,12.501563
3,Infinix,Note 5,Ice Blue,4 GB,64 GB,4.2,12999,12999,Infinix Note 5,0,0.000000
4,Apple,iPhone 11,Black,4GB,64 GB,4.6,49900,49900,Apple iPhone 11,0,0.000000
5,GIONEE,L800,Black,8 MB,16 MB,4.0,2199,2199,GIONEE L800,0,0.000000
6,Apple,iPhone 13 Mini,Pink,6 GB,512 GB,NaN,99900,99900,Apple iPhone 13 Mini,0,0.000000
7,Apple,iPhone XR,Coral,3 GB,64 GB,4.6,42999,47900,Apple iPhone XR,4901,10.231733
8,SAMSUNG,Galaxy E5,Brown,1.5 GB,16 GB,4.2,20400,20400,SAMSUNG Galaxy E5,0,0.000000
9,Xiaomi,Redmi Note 11T 5G,Aquamarine Blue,8 GB,128 GB,4.3,21736,22999,Xiaomi Redmi Note 11T 5G,1263,5.491543

In [19]:
# Remove "GB", "MB" from Memory and Storage
df['Memory'] = df['Memory'].str.replace('GB', '')
df['Memory'] = df['Memory'].str.replace('MB', '')

In [20]:
df['Storage'] = df['Storage'].str.replace('GB', '')
df['Storage'] = df['Storage'].str.replace('MB', '')

In [21]:
df.head(10)

,Brands,Models,Colors,Memory,Storage,Rating,Selling Price,Original Price,Mobile,Discount,discount percentage
0,SAMSUNG,GALAXY M31S,Mirage Black,8,128,4.3,19330,20999,SAMSUNG GALAXY M31S,1669,7.947998
1,Nokia,3.2,Steel,2,16,3.8,10199,10199,Nokia 3.2,0,0.000000
2,realme,C2,Diamond Black,2,NaN,4.4,6999,7999,realme C2,1000,12.501563
3,Infinix,Note 5,Ice Blue,4,64,4.2,12999,12999,Infinix Note 5,0,0.000000
4,Apple,iPhone 11,Black,4,64,4.6,49900,49900,Apple iPhone 11,0,0.000000
5,GIONEE,L800,Black,8,16,4.0,2199,2199,GIONEE L800,0,0.000000
6,Apple,iPhone 13 Mini,Pink,6,512,NaN,99900,99900,Apple iPhone 13 Mini,0,0.000000
7,Apple,iPhone XR,Coral,3,64,4.6,42999,47900,Apple iPhone XR,4901,10.231733
8,SAMSUNG,Galaxy E5,Brown,1.5,16,4.2,20400,20400,SAMSUNG Galaxy E5,0,0.000000
9,Xiaomi,Redmi Note 11T 5G,Aquamarine Blue,8,128,4.3,21736,22999,Xiaomi Redmi Note 11T 5G,1263,5.491543

In [25]:
# Change the datatype of Memory and storage columns to float
df['Memory'] = pd.to_numeric(df['Memory'], errors='coerce')
df['Storage'] = pd.to_numeric(df['Storage'], errors='coerce')

In [29]:
df['Storage'] = pd.to_numeric(df['Storage'], errors='coerce')
median_storage = df['Storage'].median()
if pd.isna(median_storage):
    median_storage = 0
df['Storage'] = df['Storage'].fillna(median_storage)

import numpy as np
if np.isinf(df['Storage']).any():
    df['Storage'] = df['Storage'].replace([np.inf, -np.inf], median_storage)

df['Storage'] = df['Storage'].astype(int)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 928 entries, 0 to 3106
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Brands               928 non-null    object
 1   Models               928 non-null    object
 2   Colors               928 non-null    object
 3   Memory               914 non-null    float64
 4   Storage              928 non-null    int64
 5   Rating               894 non-null    float64
 6   Selling Price        928 non-null    int64
 7   Original Price       928 non-null    int64
 8   Mobile               928 non-null    object
 9   Discount             928 non-null    int64
 10  discount percentage  928 non-null    float64
dtypes: float64(3), int64(4), object(4)
memory usage: 87.0+ KB

In [31]:
df['Memory'].fillna(df['Memory'].median(), inplace=True)
df['Storage'].fillna(df['Storage'].median(), inplace=True)

/tmp/ipykernel_1990/2251292913.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Memory'].fillna(df['Memory'].median(), inplace=True)
/tmp/ipykernel_1990/2251292913.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Storage'].fillna(df['Storage'].median(), inplace=True)

In [32]:
df.isnull().sum()

Brands                  0
Models                  0
Colors                  0
Memory                  0
Storage                 0
Rating                 34
Selling Price           0
Original Price          0
Mobile                  0
Discount                0
discount percentage     0
dtype: int64

In [33]:
df['Rating'].fillna(df['Rating'].mean(), inplace=True)

/tmp/ipykernel_1990/1501272357.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Rating'].fillna(df['Rating'].mean(), inplace=True)

In [34]:
df.isnull().sum()

Brands                 0
Models                 0
Colors                 0
Memory                 0
Storage                0
Rating                 0
Selling Price          0
Original Price         0
Mobile                 0
Discount               0
discount percentage    0
dtype: int64

In [35]:
df.head(10)

,Brands,Models,Colors,Memory,Storage,Rating,Selling Price,Original Price,Mobile,Discount,discount percentage
0,SAMSUNG,GALAXY M31S,Mirage Black,8.0,128,4.30000,19330,20999,SAMSUNG GALAXY M31S,1669,7.947998
1,Nokia,3.2,Steel,2.0,16,3.80000,10199,10199,Nokia 3.2,0,0.000000
2,realme,C2,Diamond Black,2.0,64,4.40000,6999,7999,realme C2,1000,12.501563
3,Infinix,Note 5,Ice Blue,4.0,64,4.20000,12999,12999,Infinix Note 5,0,0.000000
4,Apple,iPhone 11,Black,4.0,64,4.60000,49900,49900,Apple iPhone 11,0,0.000000
5,GIONEE,L800,Black,8.0,16,4.00000,2199,2199,GIONEE L800,0,0.000000
6,Apple,iPhone 13 Mini,Pink,6.0,512,4.15906,99900,99900,Apple iPhone 13 Mini,0,0.000000
7,Apple,iPhone XR,Coral,3.0,64,4.60000,42999,47900,Apple iPhone XR,4901,10.231733
8,SAMSUNG,Galaxy E5,Brown,1.5,16,4.20000,20400,20400,SAMSUNG Galaxy E5,0,0.000000
9,Xiaomi,Redmi Note 11T 5G,Aquamarine Blue,8.0,128,4.30000,21736,22999,Xiaomi Redmi Note 11T 5G,1263,5.491543

In [36]:
# Rename the column Memory to "RAM" and storage to "ROM"
df.rename(columns={'Memory': 'RAM', 'Storage': 'ROM'}, inplace=True)

In [37]:
df.head()

,Brands,Models,Colors,RAM,ROM,Rating,Selling Price,Original Price,Mobile,Discount,discount percentage
0,SAMSUNG,GALAXY M31S,Mirage Black,8.0,128,4.3,19330,20999,SAMSUNG GALAXY M31S,1669,7.947998
1,Nokia,3.2,Steel,2.0,16,3.8,10199,10199,Nokia 3.2,0,0.000000
2,realme,C2,Diamond Black,2.0,64,4.4,6999,7999,realme C2,1000,12.501563
3,Infinix,Note 5,Ice Blue,4.0,64,4.2,12999,12999,Infinix Note 5,0,0.000000
4,Apple,iPhone 11,Black,4.0,64,4.6,49900,49900,Apple iPhone 11,0,0.000000

In [38]:
# Limit the discount percentage values to only one decimal number
df['discount percentage'] = df['discount percentage'].apply(lambda x: round(x, 1))

In [39]:
df.head()

,Brands,Models,Colors,RAM,ROM,Rating,Selling Price,Original Price,Mobile,Discount,discount percentage
0,SAMSUNG,GALAXY M31S,Mirage Black,8.0,128,4.3,19330,20999,SAMSUNG GALAXY M31S,1669,7.9
1,Nokia,3.2,Steel,2.0,16,3.8,10199,10199,Nokia 3.2,0,0.0
2,realme,C2,Diamond Black,2.0,64,4.4,6999,7999,realme C2,1000,12.5
3,Infinix,Note 5,Ice Blue,4.0,64,4.2,12999,12999,Infinix Note 5,0,0.0
4,Apple,iPhone 11,Black,4.0,64,4.6,49900,49900,Apple iPhone 11,0,0.0

In [42]:
df.drop('Mobile', axis=1, inplace=True)

In [43]:
df.head()

,Brands,Models,Colors,RAM,ROM,Rating,Selling Price,Original Price,Discount,discount percentage
0,SAMSUNG,GALAXY M31S,Mirage Black,8.0,128,4.3,19330,20999,1669,7.9
1,Nokia,3.2,Steel,2.0,16,3.8,10199,10199,0,0.0
2,realme,C2,Diamond Black,2.0,64,4.4,6999,7999,1000,12.5
3,Infinix,Note 5,Ice Blue,4.0,64,4.2,12999,12999,0,0.0
4,Apple,iPhone 11,Black,4.0,64,4.6,49900,49900,0,0.0

In [44]:
df.shape

(928, 10)

In [45]:
# Price segment
def price_category(price):
    if price < 10000:
        return "Budget"
    elif price < 30000:
        return "Mid-Range"
    else:
        return "Premium"

df['Price_Category'] = df['Selling Price'].apply(price_category)

In [51]:
df.head()

,Brands,Models,Colors,RAM,ROM,Rating,Selling Price,Original Price,discount percentage,Price_Category,Savings
0,SAMSUNG,GALAXY M31S,Mirage Black,8.0,128,4.3,19330,20999,7.9,Mid-Range,1669
1,Nokia,3.2,Steel,2.0,16,3.8,10199,10199,0.0,Mid-Range,0
2,realme,C2,Diamond Black,2.0,64,4.4,6999,7999,12.5,Budget,1000
3,Infinix,Note 5,Ice Blue,4.0,64,4.2,12999,12999,0.0,Mid-Range,0
4,Apple,iPhone 11,Black,4.0,64,4.6,49900,49900,0.0,Premium,0

In [47]:
df['Savings'] = df['Original Price'] - df['Selling Price']

In [50]:
df.head()

,Brands,Models,Colors,RAM,ROM,Rating,Selling Price,Original Price,discount percentage,Price_Category,Savings
0,SAMSUNG,GALAXY M31S,Mirage Black,8.0,128,4.3,19330,20999,7.9,Mid-Range,1669
1,Nokia,3.2,Steel,2.0,16,3.8,10199,10199,0.0,Mid-Range,0
2,realme,C2,Diamond Black,2.0,64,4.4,6999,7999,12.5,Budget,1000
3,Infinix,Note 5,Ice Blue,4.0,64,4.2,12999,12999,0.0,Mid-Range,0
4,Apple,iPhone 11,Black,4.0,64,4.6,49900,49900,0.0,Premium,0

In [53]:
df['Has_Discount'] = df['discount percentage'].apply(
    lambda x: 1 if x > 0 else 0
)

In [54]:
df['Price_per_GB'] = df['Selling Price'] / df['ROM']

In [55]:
df.head()

,Brands,Models,Colors,RAM,ROM,Rating,Selling Price,Original Price,discount percentage,Price_Category,Savings,Has_Discount,Price_per_GB
0,SAMSUNG,GALAXY M31S,Mirage Black,8.0,128,4.3,19330,20999,7.9,Mid-Range,1669,1,151.015625
1,Nokia,3.2,Steel,2.0,16,3.8,10199,10199,0.0,Mid-Range,0,0,637.437500
2,realme,C2,Diamond Black,2.0,64,4.4,6999,7999,12.5,Budget,1000,1,109.359375
3,Infinix,Note 5,Ice Blue,4.0,64,4.2,12999,12999,0.0,Mid-Range,0,0,203.109375
4,Apple,iPhone 11,Black,4.0,64,4.6,49900,49900,0.0,Premium,0,0,779.687500

In [56]:
df['Price_per_GB'] = df['Price_per_GB'].apply(lambda x: round(x, 1))

In [57]:
df.head()

,Brands,Models,Colors,RAM,ROM,Rating,Selling Price,Original Price,discount percentage,Price_Category,Savings,Has_Discount,Price_per_GB
0,SAMSUNG,GALAXY M31S,Mirage Black,8.0,128,4.3,19330,20999,7.9,Mid-Range,1669,1,151.0
1,Nokia,3.2,Steel,2.0,16,3.8,10199,10199,0.0,Mid-Range,0,0,637.4
2,realme,C2,Diamond Black,2.0,64,4.4,6999,7999,12.5,Budget,1000,1,109.4
3,Infinix,Note 5,Ice Blue,4.0,64,4.2,12999,12999,0.0,Mid-Range,0,0,203.1
4,Apple,iPhone 11,Black,4.0,64,4.6,49900,49900,0.0,Premium,0,0,779.7

In [58]:
# Ram Category
def ram_category(ram):
    if ram <= 4:
        return "Low"
    elif ram <= 6:
        return "Medium"
    else:
        return "High"

df['RAM_Category'] = df['RAM'].apply(ram_category)

In [59]:
# Rating Category
def rating_category(r):
    if r >= 4.5:
        return "Excellent"
    elif r >= 4.0:
        return "Good"
    else:
        return "Average"

df['Rating_Category'] = df['Rating'].apply(rating_category)

In [77]:
# Unique ID for each Product
df['Product_ID'] = range(1, len(df) + 1)

In [76]:
df.head(10)

,Brands,Models,Colors,RAM,ROM,Rating,Selling Price,Original Price,discount percentage,Price_Category,Savings,Has_Discount,Price_per_GB,RAM_Category,Rating_Category,Product_ID
0,SAMSUNG,GALAXY M31S,Mirage Black,8.0,128,4.30000,19330,20999,7.9,Mid-Range,1669,1,151.0,High,Good,1
1,Nokia,3.2,Steel,2.0,16,3.80000,10199,10199,0.0,Mid-Range,0,0,637.4,Low,Average,2
2,realme,C2,Diamond Black,2.0,64,4.40000,6999,7999,12.5,Budget,1000,1,109.4,Low,Good,3
3,Infinix,Note 5,Ice Blue,4.0,64,4.20000,12999,12999,0.0,Mid-Range,0,0,203.1,Low,Good,4
4,Apple,iPhone 11,Black,4.0,64,4.60000,49900,49900,0.0,Premium,0,0,779.7,Low,Excellent,5
5,GIONEE,L800,Black,8.0,16,4.00000,2199,2199,0.0,Budget,0,0,137.4,High,Good,6
6,Apple,iPhone 13 Mini,Pink,6.0,512,4.15906,99900,99900,0.0,Premium,0,0,195.1,Medium,Good,7
7,Apple,iPhone XR,Coral,3.0,64,4.60000,42999,47900,10.2,Premium,4901,1,671.9,Low,Excellent,8
8,SAMSUNG,Galaxy E5,Brown,1.5,16,4.20000,20400,20400,0.0,Mid-Range,0,0,1275.0,Low,Good,9
9,Xiaomi,Redmi Note 11T 5G,Aquamarine Blue,8.0,128,4.30000,21736,22999,5.5,Mid-Range,1263,1,169.8,High,Good,10

In [78]:
# Ordering the Columns
df = df[
    [
        'Product_ID',
        'Brands',
        'Models',
        'Colors',
        'RAM',
        'ROM',
        'Rating',
        'Selling Price',
        'Original Price',
        'discount percentage',
        'Price_Category',
        'Savings',
        'Has_Discount',
        'Price_per_GB',
        'RAM_Category',
        'Rating_Category'
    ]
]

In [79]:
df.head()

,Product_ID,Brands,Models,Colors,RAM,ROM,Rating,Selling Price,Original Price,discount percentage,Price_Category,Savings,Has_Discount,Price_per_GB,RAM_Category,Rating_Category
0,1,SAMSUNG,GALAXY M31S,Mirage Black,8.0,128,4.3,19330,20999,7.9,Mid-Range,1669,1,151.0,High,Good
1,2,Nokia,3.2,Steel,2.0,16,3.8,10199,10199,0.0,Mid-Range,0,0,637.4,Low,Average
2,3,realme,C2,Diamond Black,2.0,64,4.4,6999,7999,12.5,Budget,1000,1,109.4,Low,Good
3,4,Infinix,Note 5,Ice Blue,4.0,64,4.2,12999,12999,0.0,Mid-Range,0,0,203.1,Low,Good
4,5,Apple,iPhone 11,Black,4.0,64,4.6,49900,49900,0.0,Premium,0,0,779.7,Low,Excellent

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 928 entries, 0 to 3106
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product_ID           928 non-null    int64
 1   Brands               928 non-null    object
 2   Models               928 non-null    object
 3   Colors               928 non-null    object
 4   RAM                  928 non-null    float64
 5   ROM                  928 non-null    int64
 6   Rating               928 non-null    float64
 7   Selling Price        928 non-null    int64
 8   Original Price       928 non-null    int64
 9   discount percentage  928 non-null    float64
 10  Price_Category       928 non-null    object
 11  Savings              928 non-null    int64
 12  Has_Discount         928 non-null    int64
 13  Price_per_GB         928 non-null    float64
 14  RAM_Category         928 non-null    object
 15  Rating_Category      928 non-null    object
dtypes: float64(4), int64(6), object(6)
memory usage: 123.2+ KB

In [81]:
df.shape

(928, 16)

In [82]:
df.to_csv(
    "final_smartphone_sales_data.csv",
    index=False
)